// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doazsojgacwzpdnltwka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYXpzb2pnYWN3enBkbmx0d2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzQyNDYsImV4cCI6MjA1MTc1MDI0Nn0.xqDB8ClGpMhLps5b_BZ6Vjn9kX5oXXPIzqEl3UShmdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);